"""Oyun durumu ve sabit veri sözlükleri."""

from __future__ import annotations

from typing import Any, Dict

# 1. İK Aday Havuzu (Personel Kartları)
EMPLOYEE_POOL: Dict[str, Dict[str, Any]] = {
    "Arda": {
        "role": "Mekanik Mühendisi",
        "skill": 92,
        "analysis": 40,
        "teamwork": 55,
        "cost": 1550,
        "avatar": "🛠️",
        "hidden_trait": "Caffeine Addict",
        "trait_description": "Caffeine Addict: Kahve yoksa verim %50 düşer.",
        "discovered": False,
    },
    "Merve": {
        "role": "Analiz Mühendisi",
        "skill": 60,
        "analysis": 95,
        "teamwork": 88,
        "cost": 1500,
        "avatar": "🔬",
        "hidden_trait": "Natural Leader",
        "trait_description": "Natural Leader: Takım sinerjisini sessizce artırır.",
        "discovered": False,
    },
    "Demir": {
        "role": "Mekanik Mühendisi",
        "skill": 85,
        "analysis": 30,
        "teamwork": 90,
        "cost": 1300,
        "avatar": "🧱",
        "hidden_trait": "Lone Wolf",
        "trait_description": "Lone Wolf: Tek başına çalışırken zirve performans.",
        "discovered": False,
    },
    "Can": {
        "role": "Süreç Mühendisi",
        "skill": 72,
        "analysis": 65,
        "teamwork": 45,
        "cost": 1050,
        "avatar": "🚚",
        "hidden_trait": "Overthinker",
        "trait_description": "Overthinker: Analiz yüksek ama teslimat yavaş.",
        "discovered": False,
    },
    "Selin": {
        "role": "Planlama Uzmanı",
        "skill": 40,
        "analysis": 85,
        "teamwork": 95,
        "cost": 950,
        "avatar": "🧰",
        "hidden_trait": "Social Butterfly",
        "trait_description": "Social Butterfly: Moral artırır ama dikkati dağıtır.",
        "discovered": False,
    },
    "Eda": {
        "role": "Genel Uzman",
        "skill": 65,
        "analysis": 60,
        "teamwork": 70,
        "cost": 800,
        "avatar": "🧩",
        "hidden_trait": "Fast Learner",
        "trait_description": "Fast Learner: Seviye ilerledikçe gelişir.",
        "discovered": False,
    },
    "Kaan": {
        "role": "Üretim Uzmanı",
        "skill": 88,
        "analysis": 70,
        "teamwork": 60,
        "cost": 1750,
        "avatar": "🌙",
        "hidden_trait": "Night Owl",
        "trait_description": "Night Owl: Gece vardiyasında verim artar.",
        "discovered": False,
    },
    "Asli": {
        "role": "Analiz Mühendisi",
        "skill": 50,
        "analysis": 92,
        "teamwork": 80,
        "cost": 1700,
        "avatar": "📐",
        "hidden_trait": "Perfectionist",
        "trait_description": "Perfectionist: Hata sıfır ama stres yüksektir.",
        "discovered": False,
    },
    "Deniz": {
        "role": "Çok Yönlü Uzman",
        "skill": 75,
        "analysis": 75,
        "teamwork": 75,
        "cost": 1650,
        "avatar": "🧠",
        "hidden_trait": "Versatile",
        "trait_description": "Versatile: Departmanlar arası ceza yok.",
        "discovered": False,
    },
    "Umut": {
        "role": "Kıdemli Uzman",
        "skill": 95,
        "analysis": 50,
        "teamwork": 40,
        "cost": 2050,
        "avatar": "🏗️",
        "hidden_trait": "Senior Specialist",
        "trait_description": "Senior Specialist: Yüksek maliyet, yüksek hassasiyet.",
        "discovered": False,
    },
    "Seda": {
        "role": "Ar-Ge Uzmanı",
        "skill": 45,
        "analysis": 98,
        "teamwork": 90,
        "cost": 2000,
        "avatar": "💡",
        "hidden_trait": "Creative Genius",
        "trait_description": "Creative Genius: Zor analitik işleri çözer.",
        "discovered": False,
    },
    "Burak": {
        "role": "Süreç Mühendisi",
        "skill": 82,
        "analysis": 82,
        "teamwork": 50,
        "cost": 1950,
        "avatar": "🎲",
        "hidden_trait": "Unpredictable",
        "trait_description": "Unpredictable: Değerler %10 dalgalanır.",
        "discovered": False,
    },
    "Nil": {
        "role": "Planlama Uzmanı",
        "skill": 60,
        "analysis": 60,
        "teamwork": 98,
        "cost": 1850,
        "avatar": "🕊️",
        "hidden_trait": "Peacekeeper",
        "trait_description": "Peacekeeper: Çatışma cezalarını önler.",
        "discovered": False,
    },
}

# 2. Level ve Kriz Verileri
LEVELS: Dict[int, Dict[str, Any]] = {
    1: {
        "name": "Level 1: Peak Hour Chaos",
        "crisis_name": "Assembly Line Pressure",
        "description": "6 aday arasından 4 kişilik ekip kur. Bütçeyi dikkatli kullan.",
        "stations": [
            {"name": "Assembly_Line", "dept": "Mekanik", "min": 70},
            {"name": "Planning_Office", "dept": "Analiz", "min": 60},
        ],
        "budget": 5000,
        "bonus_budget": 0,
        "candidates": ["Arda", "Merve", "Demir", "Can", "Selin", "Eda"],
        "hire_count": 4,
        "progress_target": 0.35,
    },
    2: {
        "name": "Level 2: Expansion Shift",
        "crisis_name": "Quality Drift Alert",
        "description": "3 aday arasından 1 kişi seç. Ekibin dengesini bozma.",
        "stations": [
            {"name": "Assembly_1", "dept": "Mekanik", "min": 75},
            {"name": "Assembly_2", "dept": "Mekanik", "min": 70},
            {"name": "Planning_Office", "dept": "Analiz", "min": 65},
        ],
        "budget": 7500,
        "bonus_budget": 0,
        "candidates": ["Kaan", "Asli", "Deniz"],
        "hire_count": 1,
        "progress_target": 0.7,
    },
    3: {
        "name": "Level 3: Full Scale Rush",
        "crisis_name": "Supply Chain Lockdown",
        "description": "4 aday arasından 2 kişi seç. Yüksek analiz puanı kritik.",
        "stations": [
            {"name": "Production_1", "dept": "Mekanik", "min": 80},
            {"name": "Production_2", "dept": "Mekanik", "min": 80},
            {"name": "R&D_Center", "dept": "Analiz", "min": 75},
            {"name": "Planning_Office", "dept": "Analiz", "min": 70},
        ],
        "budget": 12000,
        "bonus_budget": 0,
        "candidates": ["Umut", "Seda", "Burak", "Nil"],
        "hire_count": 2,
        "progress_target": 0.95,
    },
}


def discover_employee_trait(employee_name: str) -> bool:
    """Bir personelin gizli özelliğini 'keşfedildi' olarak işaretler."""
    if employee_name in EMPLOYEE_POOL:
        EMPLOYEE_POOL[employee_name]["discovered"] = True
        return True
    return False
