"""Oyun durumu ve sabit veri sözlükleri."""

from __future__ import annotations

from typing import Any, Dict

# 1. İK Aday Havuzu (Personel Kartları)
EMPLOYEE_POOL: Dict[str, Dict[str, Any]] = {
    "Arda": {
        "role": "Mechanical Engineer",
        "skill": 92,
        "analysis": 40,
        "teamwork": 55,
        "cost": 1550,
        "avatar": "🛠️",
        "hidden_trait": "Caffeine Addict",
        "trait_description": "Caffeine Addict: Kahve yoksa verim %50 düşer.",
        "discovered": False,
    },
    "Merve": {
        "role": "Analysis Engineer",
        "skill": 60,
        "analysis": 95,
        "teamwork": 88,
        "cost": 1500,
        "avatar": "🔬",
        "hidden_trait": "Natural Leader",
        "trait_description": "Natural Leader: Takım sinerjisini sessizce artırır.",
        "discovered": False,
    },
    "Demir": {
        "role": "Mechanical Engineer",
        "skill": 85,
        "analysis": 30,
        "teamwork": 90,
        "cost": 1300,
        "avatar": "🧱",
        "hidden_trait": "Lone Wolf",
        "trait_description": "Lone Wolf: Tek başına çalışırken zirve performans.",
        "discovered": False,
    },
    "Can": {
        "role": "Process Engineer",
        "skill": 72,
        "analysis": 65,
        "teamwork": 45,
        "cost": 1050,
        "avatar": "🚚",
        "hidden_trait": "Overthinker",
        "trait_description": "Overthinker: Analiz yüksek ama teslimat yavaş.",
        "discovered": False,
    },
    "Selin": {
        "role": "Planning Specialist",
        "skill": 40,
        "analysis": 85,
        "teamwork": 95,
        "cost": 950,
        "avatar": "🧰",
        "hidden_trait": "Social Butterfly",
        "trait_description": "Social Butterfly: Moral artırır ama dikkati dağıtır.",
        "discovered": False,
    },
    "Eda": {
        "role": "General Specialist",
        "skill": 65,
        "analysis": 60,
        "teamwork": 70,
        "cost": 800,
        "avatar": "🧩",
        "hidden_trait": "Fast Learner",
        "trait_description": "Fast Learner: Seviye ilerledikçe gelişir.",
        "discovered": False,
    },
    "Kaan": {
        "role": "Production Specialist",
        "skill": 88,
        "analysis": 70,
        "teamwork": 60,
        "cost": 1300,
        "avatar": "🌙",
        "hidden_trait": "Night Owl",
        "trait_description": "Night Owl: Gece vardiyasında verim artar.",
        "discovered": False,
    },
    "Asli": {
        "role": "Analysis Engineer",
        "skill": 50,
        "analysis": 92,
        "teamwork": 80,
        "cost": 1250,
        "avatar": "📐",
        "hidden_trait": "Perfectionist",
        "trait_description": "Perfectionist: Hata sıfır ama stres yüksektir.",
        "discovered": False,
    },
    "Deniz": {
        "role": "Multi-Skilled Specialist",
        "skill": 75,
        "analysis": 75,
        "teamwork": 75,
        "cost": 1200,
        "avatar": "🧠",
        "hidden_trait": "Versatile",
        "trait_description": "Versatile: Departmanlar arası ceza yok.",
        "discovered": False,
    },
    "Umut": {
        "role": "Senior Specialist",
        "skill": 95,
        "analysis": 50,
        "teamwork": 40,
        "cost": 1450,
        "avatar": "🏗️",
        "hidden_trait": "Senior Specialist",
        "trait_description": "Senior Specialist: Yüksek maliyet, yüksek hassasiyet.",
        "discovered": False,
    },
    "Seda": {
        "role": "R&D Specialist",
        "skill": 45,
        "analysis": 98,
        "teamwork": 90,
        "cost": 2000,
        "avatar": "💡",
        "hidden_trait": "Creative Genius",
        "trait_description": "Creative Genius: Zor analitik işleri çözer.",
        "discovered": False,
    },
    "Burak": {
        "role": "Process Engineer",
        "skill": 82,
        "analysis": 82,
        "teamwork": 50,
        "cost": 1950,
        "avatar": "🎲",
        "hidden_trait": "Unpredictable",
        "trait_description": "Unpredictable: Değerler %10 dalgalanır.",
        "discovered": False,
    },
    "Nil": {
        "role": "Planning Specialist",
        "skill": 60,
        "analysis": 60,
        "teamwork": 98,
        "cost": 1850,
        "avatar": "🕊️",
        "hidden_trait": "Peacekeeper",
        "trait_description": "Peacekeeper: Çatışma cezalarını önler.",
        "discovered": False,
    },
    "Emir": {
        "role": "Operations Assistant",
        "skill": 66,
        "analysis": 58,
        "teamwork": 72,
        "cost": 850,
        "avatar": "🧪",
        "hidden_trait": "Steady Worker",
        "trait_description": "Steady Worker: Stabil ama tavan performansı sınırlı.",
        "discovered": False,
    },
    "Derya": {
        "role": "Quality Assistant",
        "skill": 58,
        "analysis": 68,
        "teamwork": 64,
        "cost": 900,
        "avatar": "📋",
        "hidden_trait": "Methodical",
        "trait_description": "Methodical: Düşük maliyetle düzenli çıktı sağlar.",
        "discovered": False,
    },
}

# 2. Level ve Kriz Verileri
LEVELS: Dict[int, Dict[str, Any]] = {
    1: {
        "name": "Level 1: Peak Hour Chaos",
        "crisis_name": "Assembly Line Pressure",
        "description": "Select 4 hires from 6 candidates. Spend the budget carefully.",
        "question": "Which mix balances technical strength and analytic coverage for the first crisis?",
        "stations": [
            {"name": "Assembly_Line", "dept": "Mekanik", "min": 70},
            {"name": "Planning_Office", "dept": "Analiz", "min": 60},
        ],
        "budget": 5000,
        "bonus_budget": 0,
        "candidates": ["Arda", "Merve", "Demir", "Can", "Selin", "Eda"],
        "hire_count": 4,
        "progress_target": 0.35,
    },
    2: {
        "name": "Level 2: Expansion Shift",
        "crisis_name": "Quality Drift Alert",
        "description": "Select 2 hires from 6 candidates. Budget: +2000 ₺ (+ bonus if earned).",
        "question": "From these 6 candidates, which 2 hires best stabilize quality and speed?",
        "stations": [
            {"name": "Assembly_1", "dept": "Mekanik", "min": 75},
            {"name": "Assembly_2", "dept": "Mekanik", "min": 70},
            {"name": "Planning_Office", "dept": "Analiz", "min": 65},
        ],
        "budget": 0,
        "budget_increase": 2000,
        "bonus_budget": 0,
        "candidates": ["Kaan", "Asli", "Deniz", "Umut", "Emir", "Derya"],
        "hire_count": 2,
        "progress_target": 0.7,
    },
    3: {
        "name": "Level 3: Full Scale Rush",
        "crisis_name": "Supply Chain Lockdown",
        "description": "Select 3 hires from 6 candidates. Budget: +3000 ₺ (+ bonus if earned).",
        "question": "From these 6 candidates, which 3-person combo survives the supply lockdown?",
        "stations": [
            {"name": "Production_1", "dept": "Mekanik", "min": 80},
            {"name": "Production_2", "dept": "Mekanik", "min": 80},
            {"name": "R&D_Center", "dept": "Analiz", "min": 75},
            {"name": "Planning_Office", "dept": "Analiz", "min": 70},
        ],
        "budget": 0,
        "budget_increase": 3000,
        "bonus_budget": 0,
        "candidates": ["Asli", "Deniz", "Seda", "Burak", "Nil", "Derya"],
        "hire_count": 3,
        "progress_target": 0.95,
    },
}


def discover_employee_trait(employee_name: str) -> bool:
    """Bir personelin gizli özelliğini 'keşfedildi' olarak işaretler."""
    if employee_name in EMPLOYEE_POOL:
        EMPLOYEE_POOL[employee_name]["discovered"] = True
        return True
    return False
